# Generated by Django 3.1.4 on 2020-12-17 04:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produto', models.CharField(blank=True, max_length=10)),
                ('nome_produto', models.CharField(max_length=255)),
                ('codigo_fabricante_produto', models.CharField(blank=True, max_length=50)),
                ('descricao_produto', models.TextField(blank=True, max_length=500)),
                ('codigo_ean_produto', models.IntegerField(blank=True, default=0)),
                ('codigo_ncm_produto', models.IntegerField(blank=True, default=0)),
                ('preco_venda_produto', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('preco_compra_produto', models.FloatField(max_length=10)),
                ('quantidade_produto', models.FloatField(blank=True, max_length=10)),
                ('tipo_volume_produto', models.CharField(choices=[('UNIDADE', 'UNIDADE'), ('GRAMA', 'GRAMA'), ('PACOTE', 'PACOTE'), ('PAR', 'PAR'), ('CONJUNTO', 'CONJUNTO'), ('ML', 'ML'), ('KILOGRAMA', 'KILOGRAMA'), ('TONELADA', 'TONELADA'), ('LITRO', 'LITRO'), ('CAIXA', 'CAIXA'), ('SACO', 'SACO'), ('LATA', 'LATA'), ('KIT', 'KIT'), ('DÚZIA', 'DÚZIA'), ('DEZENA', 'DEZENA'), ('CENTENA', 'CENTENA'), ('MILHAR', 'MILHAR'), ('FARDO', 'FARDO')], default=None, max_length=20)),
                ('cor_produto', models.CharField(blank=True, max_length=50)),
                ('referencia_produto', models.CharField(blank=True, max_length=250)),
                ('localizacao_produto', models.CharField(blank=True, max_length=100)),
                ('observacao_produto', models.TextField(blank=True, max_length=500)),
                ('data_cadastro_produto', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
