# Generated by Django 3.1.4 on 2020-12-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berbin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_ncm_produto',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
