# Generated by Django 3.1.4 on 2020-12-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berbin', '0002_auto_20201217_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='codigo_ean_produto',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_ncm_produto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
