# Generated by Django 3.1.4 on 2020-12-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berbin', '0003_auto_20201221_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='conteudo_produto',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
